// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: traffic.proto

package ztpbf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// -->用于请求map spots点, request 和 response 是同一个结构
type ReqPathSpots struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId       string `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`                    //请求的车辆ID,用字符串适合多系统并用
	MissionId     string `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`              //任务ID，仅仅显示
	ExpireSeconds int32  `protobuf:"varint,3,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"` //过期时间
	// int32 startstamp = 4;//seconds
	AgvType       int32    `protobuf:"varint,5,opt,name=agv_type,json=agvType,proto3" json:"agv_type,omitempty"`                    //0 默认agv，1: iagv, 2 sagv(二维码车)
	PathSpotsLeft []string `protobuf:"bytes,6,rep,name=path_spots_left,json=pathSpotsLeft,proto3" json:"path_spots_left,omitempty"` //路径剩余点数，
	RequestSpots  []string `protobuf:"bytes,7,rep,name=request_spots,json=requestSpots,proto3" json:"request_spots,omitempty"`      //[in/out]准备请求的点,能占用希望都占到，空的话表示要一次性请求到多有的点，请求到的点保存到这里更新
	ReqMinCount   int32    `protobuf:"varint,8,opt,name=req_min_count,json=reqMinCount,proto3" json:"req_min_count,omitempty"`      //一次性请求的点的个数,0表示没有限制，非0表示这些点需要一次性都请求到,没请都求到，则回退到初始状态。
	// int32 map_id = 8;
	// repeated int32 req_spot_ids = 9;
	// int32 command = 11;//请求点位的指令
	FinishType int32 `protobuf:"varint,12,opt,name=finish_type,json=finishType,proto3" json:"finish_type,omitempty"` //[out]请求指令的完成状况
	// int32 pathsLength = 13;//整条路径的长度
	// int32 pathIndex = 14;//目前车辆所在或者已走过点位的index;
	HasTwoWay bool `protobuf:"varint,13,opt,name=has_two_way,json=hasTwoWay,proto3" json:"has_two_way,omitempty"` //道路类型 0 全部是单向路径；1 有双向路径点
}

func (x *ReqPathSpots) Reset() {
	*x = ReqPathSpots{}
	if protoimpl.UnsafeEnabled {
		mi := &file_traffic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPathSpots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPathSpots) ProtoMessage() {}

func (x *ReqPathSpots) ProtoReflect() protoreflect.Message {
	mi := &file_traffic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPathSpots.ProtoReflect.Descriptor instead.
func (*ReqPathSpots) Descriptor() ([]byte, []int) {
	return file_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPathSpots) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *ReqPathSpots) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *ReqPathSpots) GetExpireSeconds() int32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

func (x *ReqPathSpots) GetAgvType() int32 {
	if x != nil {
		return x.AgvType
	}
	return 0
}

func (x *ReqPathSpots) GetPathSpotsLeft() []string {
	if x != nil {
		return x.PathSpotsLeft
	}
	return nil
}

func (x *ReqPathSpots) GetRequestSpots() []string {
	if x != nil {
		return x.RequestSpots
	}
	return nil
}

func (x *ReqPathSpots) GetReqMinCount() int32 {
	if x != nil {
		return x.ReqMinCount
	}
	return 0
}

func (x *ReqPathSpots) GetFinishType() int32 {
	if x != nil {
		return x.FinishType
	}
	return 0
}

func (x *ReqPathSpots) GetHasTwoWay() bool {
	if x != nil {
		return x.HasTwoWay
	}
	return false
}

var File_traffic_proto protoreflect.FileDescriptor

var file_traffic_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x7a, 0x74, 0x70, 0x62, 0x66, 0x22, 0xbc, 0x02, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50, 0x61,
	0x74, 0x68, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x76, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x76, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x73, 0x70, 0x6f, 0x74,
	0x73, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61,
	0x74, 0x68, 0x53, 0x70, 0x6f, 0x74, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x70, 0x6f, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x70, 0x6f, 0x74, 0x73,
	0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x4d, 0x69, 0x6e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x5f, 0x74, 0x77, 0x6f,
	0x5f, 0x77, 0x61, 0x79, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x54,
	0x77, 0x6f, 0x57, 0x61, 0x79, 0x42, 0x1b, 0x0a, 0x0f, 0x7a, 0x6b, 0x74, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x2e, 0x7a, 0x74, 0x70, 0x62, 0x66, 0x48, 0x03, 0x5a, 0x06, 0x2f, 0x7a, 0x74, 0x70,
	0x62, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_traffic_proto_rawDescOnce sync.Once
	file_traffic_proto_rawDescData = file_traffic_proto_rawDesc
)

func file_traffic_proto_rawDescGZIP() []byte {
	file_traffic_proto_rawDescOnce.Do(func() {
		file_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(file_traffic_proto_rawDescData)
	})
	return file_traffic_proto_rawDescData
}

var file_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_traffic_proto_goTypes = []interface{}{
	(*ReqPathSpots)(nil), // 0: ztpbf.ReqPathSpots
}
var file_traffic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_traffic_proto_init() }
func file_traffic_proto_init() {
	if File_traffic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_traffic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPathSpots); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_traffic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_traffic_proto_goTypes,
		DependencyIndexes: file_traffic_proto_depIdxs,
		MessageInfos:      file_traffic_proto_msgTypes,
	}.Build()
	File_traffic_proto = out.File
	file_traffic_proto_rawDesc = nil
	file_traffic_proto_goTypes = nil
	file_traffic_proto_depIdxs = nil
}
